services:
  - type: web
    name: ai-pencil-sketch
    env: python
    region: oregon          # or your preferred region
    plan: free              # or hobby, etc.
    buildCommand: pip install -r requirements.txt
    startCommand: bash backend/start.sh  # make sure it's in the backend folder
    autoDeploy: true
